name: Docker Image CI

on:
  push:
    branches: [ "docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the new commit
      uses: actions/checkout@v4
    - name: Log in to docker hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build ./docker -t --no-cache polypode/hes:latest
    - name: Push the docker image to docker hub
      run: docker push polypode/hes:latest
